name: jleahred_github_io
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  markdown: any
  polymer: any
  script_inliner: any
  timeline:
      git: https://github.com/jleahred/timeline.git
transformers:
- script_inliner
- polymer:
    entry_points: web/timeline/index.html
